name: Handle new case files

on:
  issues: 
    types: [opened, edited]

jobs:
  new-case-file:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
    - name: Run parser
      run: |
        python3 automation/issue.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
